CREATE DATABASE hahn_software;

CREATE TABLE `hahn_software`.`PRODUCT` (
    `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT,
    `PRICE` DOUBLE NOT NULL,
    `QUANTITY` BIGINT NOT NULL,
    `DATE_CREATION` DATETIME NOT NULL,
    `USER_CREATION` BIGINT,
    `DATE_UPDATE` DATETIME,
    `USER_UPDATE` BIGINT
);
