CREATE DATABASE hahn_software;


CREATE TABLE `hahn_software`.`product` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` TEXT,
  `PRICE` DOUBLE NOT NULL,
  `QUANTITY` BIGINT NOT NULL,
  `DATE_CREATION` datetime DEFAULT (now()),
  `USER_CREATION` bigint DEFAULT NULL,
  `DATE_UPDATE` datetime DEFAULT NULL,
  `USER_UPDATE` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`)
); 

